// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: player_movements.proto

package player_movement

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PlayerPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	X    float32 `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y    float32 `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *PlayerPosition) Reset() {
	*x = PlayerPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_player_movements_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerPosition) ProtoMessage() {}

func (x *PlayerPosition) ProtoReflect() protoreflect.Message {
	mi := &file_player_movements_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerPosition.ProtoReflect.Descriptor instead.
func (*PlayerPosition) Descriptor() ([]byte, []int) {
	return file_player_movements_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerPosition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerPosition) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerPosition) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_player_movements_proto protoreflect.FileDescriptor

var file_player_movements_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x40, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x32, 0x6a, 0x0a, 0x0e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x58, 0x0a, 0x12,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x79,
	0x6e, 0x63, 0x12, 0x1e, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x6d, 0x6f, 0x76, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x1a, 0x1e, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x6d, 0x6f, 0x76, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x28, 0x01, 0x30, 0x01, 0x42, 0x4a, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x64, 0x61, 0x6c, 0x6d, 0x61, 0x73, 0x73, 0x6f, 0x2f, 0x77,
	0x6f, 0x72, 0x6c, 0x64, 0x2d, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x72, 0x73, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2d, 0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x3b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_player_movements_proto_rawDescOnce sync.Once
	file_player_movements_proto_rawDescData = file_player_movements_proto_rawDesc
)

func file_player_movements_proto_rawDescGZIP() []byte {
	file_player_movements_proto_rawDescOnce.Do(func() {
		file_player_movements_proto_rawDescData = protoimpl.X.CompressGZIP(file_player_movements_proto_rawDescData)
	})
	return file_player_movements_proto_rawDescData
}

var file_player_movements_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_player_movements_proto_goTypes = []interface{}{
	(*PlayerPosition)(nil), // 0: playermovement.PlayerPosition
}
var file_player_movements_proto_depIdxs = []int32{
	0, // 0: playermovement.PlayerMovement.PlayerPositionSync:input_type -> playermovement.PlayerPosition
	0, // 1: playermovement.PlayerMovement.PlayerPositionSync:output_type -> playermovement.PlayerPosition
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_player_movements_proto_init() }
func file_player_movements_proto_init() {
	if File_player_movements_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_player_movements_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_player_movements_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_player_movements_proto_goTypes,
		DependencyIndexes: file_player_movements_proto_depIdxs,
		MessageInfos:      file_player_movements_proto_msgTypes,
	}.Build()
	File_player_movements_proto = out.File
	file_player_movements_proto_rawDesc = nil
	file_player_movements_proto_goTypes = nil
	file_player_movements_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PlayerMovementClient is the client API for PlayerMovement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlayerMovementClient interface {
	PlayerPositionSync(ctx context.Context, opts ...grpc.CallOption) (PlayerMovement_PlayerPositionSyncClient, error)
}

type playerMovementClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayerMovementClient(cc grpc.ClientConnInterface) PlayerMovementClient {
	return &playerMovementClient{cc}
}

func (c *playerMovementClient) PlayerPositionSync(ctx context.Context, opts ...grpc.CallOption) (PlayerMovement_PlayerPositionSyncClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PlayerMovement_serviceDesc.Streams[0], "/playermovement.PlayerMovement/PlayerPositionSync", opts...)
	if err != nil {
		return nil, err
	}
	x := &playerMovementPlayerPositionSyncClient{stream}
	return x, nil
}

type PlayerMovement_PlayerPositionSyncClient interface {
	Send(*PlayerPosition) error
	Recv() (*PlayerPosition, error)
	grpc.ClientStream
}

type playerMovementPlayerPositionSyncClient struct {
	grpc.ClientStream
}

func (x *playerMovementPlayerPositionSyncClient) Send(m *PlayerPosition) error {
	return x.ClientStream.SendMsg(m)
}

func (x *playerMovementPlayerPositionSyncClient) Recv() (*PlayerPosition, error) {
	m := new(PlayerPosition)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PlayerMovementServer is the server API for PlayerMovement service.
type PlayerMovementServer interface {
	PlayerPositionSync(PlayerMovement_PlayerPositionSyncServer) error
}

// UnimplementedPlayerMovementServer can be embedded to have forward compatible implementations.
type UnimplementedPlayerMovementServer struct {
}

func (*UnimplementedPlayerMovementServer) PlayerPositionSync(PlayerMovement_PlayerPositionSyncServer) error {
	return status.Errorf(codes.Unimplemented, "method PlayerPositionSync not implemented")
}

func RegisterPlayerMovementServer(s *grpc.Server, srv PlayerMovementServer) {
	s.RegisterService(&_PlayerMovement_serviceDesc, srv)
}

func _PlayerMovement_PlayerPositionSync_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PlayerMovementServer).PlayerPositionSync(&playerMovementPlayerPositionSyncServer{stream})
}

type PlayerMovement_PlayerPositionSyncServer interface {
	Send(*PlayerPosition) error
	Recv() (*PlayerPosition, error)
	grpc.ServerStream
}

type playerMovementPlayerPositionSyncServer struct {
	grpc.ServerStream
}

func (x *playerMovementPlayerPositionSyncServer) Send(m *PlayerPosition) error {
	return x.ServerStream.SendMsg(m)
}

func (x *playerMovementPlayerPositionSyncServer) Recv() (*PlayerPosition, error) {
	m := new(PlayerPosition)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PlayerMovement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "playermovement.PlayerMovement",
	HandlerType: (*PlayerMovementServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PlayerPositionSync",
			Handler:       _PlayerMovement_PlayerPositionSync_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "player_movements.proto",
}
